### ISSUE TITLE
Reporte de Practica 2

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-equipohjf#2]
El Estudiante realiza una práctica 2 de la usabilidad de una Interfaz gráfica en Visual Studio con sus características para su implementación.

1. La interfaz gráfica debe realizarse en Visual Studio para implementar controles, botones y eventos.

2. La interfaz grafica  a diseñar puede ser una calculadora o algún otra Aplicación

3. La interfaz grafica a diseñar debe reunir los requisitos de Usuabilidad y diseño

4. Indicar  en el reporte de práctica las características de la Usuabilidad  y diseño

**Comment by Heidi-19** [comment]
[Practica 2 - Interfaz en Visual Studio.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-equipohjf/files/8085854/Practica.2.-.Interfaz.en.Visual.Studio.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Practica 2 (Federico Victoriano Sierra(4US)).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-equipohjf/files/8085857/Practica.2.Federico.Victoriano.Sierra.4US.pdf)

**Comment by JoseABCruz** [comment]
[Practica 2_BalbuenaCruzJoséAntonio.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-equipohjf/files/8085948/Practica.2_BalbuenaCruzJoseAntonio.pdf)

**Comment by IrvingFernand0** [comment]
Calificación practica 2: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
